random_state: 42
test_size: 0.15
val_size: 0.15

model:
  name: "random_forest"

  random_forest:
    n_estimators: 300
    max_depth: null
    min_samples_split: 4
    min_samples_leaf: 2
    n_jobs: -1

  grad_boost:
    n_estimators: 400
    learning_rate: 0.05
    max_depth: 3

  xgboost:
    n_estimators: 600
    learning_rate: 0.05
    max_depth: 6
    subsample: 0.8
    colsample_bytree: 0.8

# 🧹 Preprocessing Settings
preprocessing:
  drop_columns: ["Route"]
  fill_values:
    Additional_Info: "NA"